# Generated by Django 2.2 on 2019-04-17 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64, verbose_name='Nome do Estudante')),
                ('matricula', models.CharField(blank=True, max_length=20, null=True, verbose_name='Matrícula')),
                ('estiloInput', models.CharField(blank=True, choices=[('Verbal', 'Verbal'), ('Visual', 'Visual')], max_length=255, null=True, verbose_name='Estilos de Aprendizagem: entrada')),
                ('estiloUnderstanding', models.CharField(blank=True, choices=[('Verbal', 'Verbal'), ('Visual', 'Visual')], max_length=255, null=True, verbose_name='Estilos de Aprendizagem: entendimento')),
                ('estiloPercpetion', models.CharField(blank=True, choices=[('Verbal', 'Verbal'), ('Visual', 'Visual')], max_length=255, null=True, verbose_name='Estilos de Aprendizagem: percepção')),
                ('estiloProcessing', models.CharField(blank=True, choices=[('Verbal', 'Verbal'), ('Visual', 'Visual')], max_length=255, null=True, verbose_name='Estilos de Aprendizagem: processamento')),
                ('usuario', models.CharField(blank=True, max_length=20, null=True, verbose_name='Usuário')),
                ('senha', models.CharField(blank=True, max_length=20, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('isActive', models.BooleanField(default=True)),
                ('createdBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
