# Generated by Django 2.2 on 2019-04-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='createdBy',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='isActive',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='estiloPercpetion',
            field=models.CharField(blank=True, choices=[('Intuitivo', 'Intuitivo'), ('Sensitivo', 'Sensitivo')], max_length=255, null=True, verbose_name='Estilos de Aprendizagem: percepção'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='estiloProcessing',
            field=models.CharField(blank=True, choices=[('Ativo', 'Ativo'), ('Reflexivo', 'Reflexivo')], max_length=255, null=True, verbose_name='Estilos de Aprendizagem: processamento'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='estiloUnderstanding',
            field=models.CharField(blank=True, choices=[('Sequencial', 'Sequencial'), ('Global', 'Global')], max_length=255, null=True, verbose_name='Estilos de Aprendizagem: entendimento'),
        ),
    ]
