# Generated by Django 2.2 on 2019-04-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20190417_1940'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdealLO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='instance_name')),
                ('concept', models.CharField(blank=True, max_length=255, null=True, verbose_name='concept')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='description')),
                ('interactivity_type', models.CharField(blank=True, choices=[('active', 'ative'), ('expositive', 'expositive'), ('mixed', 'mixed')], max_length=255, null=True, verbose_name='interactivity_type')),
                ('learn_resource_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='learn_resource_type')),
                ('interactivity_level', models.CharField(blank=True, choices=[('very low', 'very low'), ('low', 'low'), ('medium', 'medium'), ('high', 'high'), ('very high', 'very high')], max_length=255, null=True, verbose_name='interactivity_level')),
                ('semantic_density', models.CharField(blank=True, choices=[('very low', 'very low'), ('low', 'low'), ('medium', 'medium'), ('high', 'high'), ('very high', 'very high')], max_length=255, null=True, verbose_name='semantic_density')),
                ('difficulty', models.CharField(blank=True, choices=[('very easy', 'very easy'), ('easy', 'easy'), ('medium', 'medium'), ('difficult', 'difficult'), ('very difficult', 'very difficult')], max_length=255, null=True, verbose_name='difficulty')),
                ('quality', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
