# Generated by Django 2.2 on 2019-04-29 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_ideallo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crlo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_aluno_crlo', to='backend.Aluno')),
                ('idealLO', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lead_idealLO_crlo', to='backend.IdealLO')),
            ],
        ),
    ]
