# Generated by Django 2.2.1 on 2019-06-30 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_crlo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='estiloPercpetion',
            field=models.CharField(blank=True, choices=[('Intuitive', 'Intuitive'), ('Sensing', 'Sensing')], max_length=255, null=True, verbose_name='Estilos de Aprendizagem: percepção'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='estiloProcessing',
            field=models.CharField(blank=True, choices=[('ActiveProcessing', 'ActiveProcessing'), ('Reflexive', 'Reflexive')], max_length=255, null=True, verbose_name='Estilos de Aprendizagem: processamento'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='estiloUnderstanding',
            field=models.CharField(blank=True, choices=[('Sequential', 'Sequential'), ('Global', 'Global')], max_length=255, null=True, verbose_name='Estilos de Aprendizagem: entendimento'),
        ),
        migrations.AlterField(
            model_name='ideallo',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('VeryEasy', 'VeryEasy'), ('Easy', 'Easy'), ('Medium', 'Medium'), ('Difficult', 'Difficult'), ('VeryDifficult', 'VeryDifficult')], max_length=255, null=True, verbose_name='difficulty'),
        ),
        migrations.AlterField(
            model_name='ideallo',
            name='interactivity_level',
            field=models.CharField(blank=True, choices=[('VeryLow', 'VeryLow'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('VeryHigh', 'VeryHigh')], max_length=255, null=True, verbose_name='interactivity_level'),
        ),
        migrations.AlterField(
            model_name='ideallo',
            name='interactivity_type',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Expositive', 'Expositive'), ('Mixed', 'Mixed')], max_length=255, null=True, verbose_name='interactivity_type'),
        ),
        migrations.AlterField(
            model_name='ideallo',
            name='semantic_density',
            field=models.CharField(blank=True, choices=[('VeryLow', 'VeryLow'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('VeryHigh', 'VeryHigh')], max_length=255, null=True, verbose_name='semantic_density'),
        ),
    ]
